Array_Adition_With_Macro:
	nasm -felf32 -Fdwarf -g Array_Adition_With_Macro.asm
	gcc -m32 Array_Adition_With_Macro.o -o Array_Adition_With_Macro

Array_Avrege_With_Macro:
	nasm -felf32 -Fdwarf -g Array_Avrege_With_Macro.asm
	gcc -m32 Array_Avrege_With_Macro.o -o Array_Avrege_With_Macro

Array_Copy_With_Macro:
	nasm -felf32 -Fdwarf -g Array_Copy_With_Macro.asm
	gcc -m32 Array_Copy_With_Macro.o -o Array_Copy_With_Macro

Array_Count_With_Macro:
	nasm -felf32 -Fdwarf -g Array_Count_With_Macro.asm
	gcc -m32 Array_Count_With_Macro.o -o Array_Count_With_Macro

Array_Max_With_Macro:
	nasm -felf32 -Fdwarf -g Array_Max_With_Macro.asm
	gcc -m32 Array_Max_With_Macro.o -o Array_Max_With_Macro

Combination_With_Macro:
	nasm -felf32 -Fdwarf -g Combination_With_Macro.asm
	gcc -m32 Combination_With_Macro.o -o Combination_With_Macro

Factorial_With_Macro:
	nasm -felf32 -Fdwarf -g Factorial_With_Macro.asm
	gcc -m32 Factorial_With_Macro.o -o Factorial_With_Macro

Fibonacci_Series_With_Macro:
	nasm -felf32 -Fdwarf -g Fibonacci_Series_With_Macro.asm
	gcc -m32 Fibonacci_Series_With_Macro.o -o Fibonacci_Series_With_Macro 

GCD_With_Macro:
	nasm -felf32 -Fdwarf -g GCD_With_Macro.asm
	gcc -m32 GCD_With_Macro.o -o GCD_With_Macro

Perfect_Number_With_Macro:
	nasm -felf32 -Fdwarf -g Perfect_Number_With_Macro.asm
	gcc -m32 Perfect_Number_With_Macro.o -o Perfect_Number_With_Macro

Permutations_With_Macro:
	nasm -felf32 -Fdwarf -g Permutations_With_Macro.asm
	gcc -m32 Permutations_With_Macro.o -o Permutations_With_Macro

String_Concat_With_Macro:
	nasm -felf32 -Fdwarf -g String_Concat_With_Macro.asm
	gcc -m32 String_Concat_With_Macro.o -o String_Concat_With_Macro

String_Copy_With_Macro:
	nasm -felf32 -Fdwarf -g String_Copy_With_Macro.asm
	gcc -m32 String_Copy_With_Macro.o -o String_Copy_With_Macro

String_length_With_Macro:
	nasm -felf32 -Fdwarf -g String_length_With_Macro.asm
	gcc -m32 String_length_With_Macro.o -o String_length_With_Macro

String_Palindrome_With_Macro:
	nasm -felf32 -Fdwarf -g String_Palindrome_With_Macro.asm
	gcc -m32 String_Palindrome_With_Macro.o -o String_Palindrome_With_Macro

String_Reverce_With_Macro:
	nasm -felf32 -Fdwarf -g String_Reverce_With_Macro.asm
	gcc -m32 String_Reverce_With_Macro.o -o String_Reverce_With_Macro

String_Substring_With_Macro:
	nasm -felf32 -Fdwarf -g String_Substring_With_Macro.asm
	gcc -m32 String_Substring_With_Macro.o -o String_Substring_With_Macro




clean:
	rm *.o
