Fire_Crakcers_01:
	nasm -felf32 -Fdwarf -g Fire_Crakcers_01.asm
	gcc -m32 Fire_Crakcers_01.o -o Fire_Crakcers_01

Fire_Crakcers_02:
	nasm -felf32 -Fdwarf -g Fire_Crakcers_02.asm
	gcc -m32 Fire_Crakcers_02.o -o Fire_Crakcers_02

Fire_Crakcers_03:
	nasm -felf32 -Fdwarf -g Fire_Crakcers_03.asm
	gcc -m32 Fire_Crakcers_03.o -o Fire_Crakcers_03

Fire_Crakcers_04:
	nasm -felf32 -Fdwarf -g Fire_Crakcers_04.asm
	gcc -m32 Fire_Crakcers_04.o -o Fire_Crakcers_04

Fire_Crakcers_05:
	nasm -felf32 -Fdwarf -g Fire_Crakcers_05.asm
	gcc -m32 Fire_Crakcers_05.o -o Fire_Crakcers_05

clean:
	rm *.o
