Matrix_Addition:
	nasm -felf32 -Fdwarf -g Matrix_Addition.asm
	gcc -m32 Matrix_Addition.o -o Matrix_Addition

Matrix_Multiplication:
	nasm -felf32 -Fdwarf -g Matrix_Multiplication.asm
	gcc -m32 Matrix_Multiplication.o -o Matrix_Multiplication

Matrix_Sutraction:
	nasm -felf32 -Fdwarf -g Matrix_Sutraction.asm
	gcc -m32 Matrix_Sutraction.o -o Matrix_Sutraction

Matrix_Transpose:
	nasm -felf32 -Fdwarf -g Matrix_Transpose.asm
	gcc -m32 Matrix_Transpose.o -o Matrix_Transpose

clean:
	rm *.o
