Combination:
	nasm -felf32 -Fdwarf -g Combination.asm
	gcc -m32 Combination.o -o Combination

Factorial:
	nasm -felf32 -Fdwarf -g Factorial.asm
	gcc -m32 Factorial.o -o Factorial

Fibonacci_Series:
	nasm -felf32 -Fdwarf -g Fibonacci_Series.asm
	gcc -m32 Fibonacci_Series.o -o Fibonacci_Series

GCD:
	nasm -felf32 -Fdwarf -g GCD.asm
	gcc -m32 GCD.o -o GCD

Max_Two_Number:
	nasm -felf32 -Fdwarf -g Max_Two_Number.asm
	gcc -m32 Max_Two_Number.o -o Max_Two_Number

Min_Two_Number:
	nasm -felf32 -Fdwarf -g Min_Two_Number.asm
	gcc -m32 Min_Two_Number.o -o Min_Two_Numbe

Perfect_Number:
	nasm -felf32 -Fdwarf -g Perfect_Number.asm
	gcc -m32 Perfect_Number.o -o Perfect_Number

Permutations_Without_Repetition:
	nasm -felf32 -Fdwarf -g Permutations_Without_Repetition.asm
	gcc -m32 Permutations_Without_Repetition.o -o Permutations_Without_Repetition

Permutations_With_Repetition:
	nasm -felf32 -Fdwarf -g Permutations_With_Repetition.asm
	gcc -m32 Permutations_With_Repetition.o -o Permutations_With_Repetition

Prime_Number:
	nasm -felf32 -Fdwarf -g Prime_Number.asm
	gcc -m32 Prime_Number.o -o Prime_Number

clean:
	rm *.o
