String_Concat:
	nasm -felf32 -Fdwarf -g String_Concat.asm
	gcc -m32 String_Concat.o -o String_Concat

String_Copy:
	nasm -felf32 -Fdwarf -g String_Copy.asm
	gcc -m32 String_Copy.o -o String_Copy

String_length:
	nasm -felf32 -Fdwarf -g String_length.asm
	gcc -m32 String_length.o -o String_length

String_Palindrome:
	nasm -felf32 -Fdwarf -g String_Palindrome.asm
	gcc -m32 String_Palindrome.o -o String_Palindrome

String_Reverce:
	nasm -felf32 -Fdwarf -g String_Reverce.asm
	gcc -m32 String_Reverce.o -o String_Reverce

String_Substring:
	nasm -felf32 -Fdwarf -g String_Substring.asm
	gcc -m32 String_Substring.o -o String_Substring


clean:
	rm *.o
