Array_Adition:
	nasm -felf32 -Fdwarf -g Array_Adition.asm
	gcc -m32 Array_Adition.o -o Array_Adition

Array_Avrege:
	nasm -felf32 -Fdwarf -g Array_Avrege.asm
	gcc -m32 Array_Avrege.o -o Array_Avrege

Array_Copy:
	nasm -felf32 -Fdwarf -g Array_Copy.asm
	gcc -m32 Array_Copy.o -o Array_Copy 

Array_Count:
	nasm -felf32 -Fdwarf -g Array_Count.asm
	gcc -m32 Array_Count.o -o Array_Count

Array_Marge:
	nasm -felf32 -Fdwarf -g Array_Marge.asm
	gcc -m32 Array_Marge.o -o Array_Marge

Array_Max:
	nasm -felf32 -Fdwarf -g Array_Max.asm
	gcc -m32 Array_Max.o -o Array_Max

Array_Min:
	nasm -felf32 -Fdwarf -g Array_Min.asm
	gcc -m32 Array_Min.o -o Array_Min

Array_Mul:
	nasm -felf32 -Fdwarf -g Array_Mul.asm
	gcc -m32 Array_Mul.o -o Array_Mul

Array_Odd_Even_Number:
	nasm -felf32 -Fdwarf -g Array_Odd_Even_Number.asm
	gcc -m32 Array_Odd_Even_Number.o -o Array_Odd_Even_Number


Array_Search:
	nasm -felf32 -Fdwarf -g Array_Search.asm
	gcc -m32 Array_Search.o -o Array_Search

Array_Sorting:
	nasm -felf32 -Fdwarf -g Array_Sorting.asm
	gcc -m32 Array_Sorting.o -o Array_Sorting

Array_Sub:
	nasm -felf32 -Fdwarf -g Array_Sub.asm
	gcc -m32 Array_Sub.o -o Array_Sub

Array_Sum:
	nasm -felf32 -Fdwarf -g Array_Sum.asm
	gcc -m32 Array_Sum.o -o Array_Sum


clean:
	rm *.o
